# Generated by Django 2.0.4 on 2018-09-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dustbin',
            fields=[
                ('dustbin_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('filled_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('spoc', models.CharField(max_length=30)),
                ('no_of_vehicles', models.PositiveSmallIntegerField()),
                ('street_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('profession', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('mobile_number', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('aadhar_number', models.DecimalField(decimal_places=0, max_digits=12, unique=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citySmart.House')),
            ],
        ),
        migrations.CreateModel(
            name='Street_light',
            fields=[
                ('light_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('live_status', models.CharField(choices=[('ALIVE', 'alive'), ('SICK', 'sick'), ('DEAD', 'dead')], default='DEAD', max_length=5)),
                ('running_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Water_tank',
            fields=[
                ('water_tank_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('filled_percentage', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('person_incharge', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='water_tank',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citySmart.Zone'),
        ),
        migrations.AddField(
            model_name='street_light',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citySmart.Zone'),
        ),
        migrations.AddField(
            model_name='house',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citySmart.Zone'),
        ),
        migrations.AddField(
            model_name='dustbin',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citySmart.Zone'),
        ),
    ]
