# Generated by Django 2.0.4 on 2019-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citySmart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street_light',
            name='live_status',
        ),
        migrations.AddField(
            model_name='street_light',
            name='health',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
