# Generated by Django 2.0.4 on 2018-09-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citySmart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='number',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='zone',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='street_light',
            old_name='light_id',
            new_name='street_light_id',
        ),
    ]
