# Generated by Django 2.0.4 on 2018-09-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citySmart', '0002_auto_20180924_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='street_light',
            old_name='street_light_id',
            new_name='light_id',
        ),
    ]
