# Generated by Django 2.0.4 on 2018-09-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citySmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(choices=[('Secretary', 'Secretary'), ('ZoneHead', 'ZoneHead')], max_length=12)),
                ('secret_key', models.CharField(blank=True, max_length=16)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citySmart.Zone')),
            ],
        ),
    ]
