# Generated by Django 2.0.4 on 2018-09-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_security', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='zone_id',
            new_name='zone',
        ),
    ]
