# Generated by Django 2.0.4 on 2018-09-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='secret_key',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
