# Generated by Django 2.0.4 on 2018-09-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_security', '0003_token_token_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token_history',
            new_name='Token_usage_history',
        ),
    ]
