# Generated by Django 2.0.4 on 2018-10-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_security', '0004_auto_20180929_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='key',
            new_name='tkn_key',
        ),
    ]
