# Generated by Django 2.0.4 on 2018-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testapi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
