# Generated by Django 2.0.4 on 2018-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapi',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
