# Generated by Django 2.0.4 on 2019-02-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testapi',
        ),
    ]
